/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2_estructura;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Principal extends javax.swing.JFrame {
    List caballosBlancos = new List();
    List caballosNegros = new List();
    List peonesBlancos = new List();
    List peonesNegros = new List();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        JLabel tmp = this.background;
        this.back.remove(this.back.getComponentCount() - 1);
        this.back.add(tmp, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        back = new javax.swing.JInternalFrame();
        B_4 = new javax.swing.JLabel();
        C_4 = new javax.swing.JLabel();
        D_4 = new javax.swing.JLabel();
        E_4 = new javax.swing.JLabel();
        F_4 = new javax.swing.JLabel();
        H_4 = new javax.swing.JLabel();
        G_4 = new javax.swing.JLabel();
        H_3 = new javax.swing.JLabel();
        G_3 = new javax.swing.JLabel();
        F_3 = new javax.swing.JLabel();
        D_3 = new javax.swing.JLabel();
        A_8 = new javax.swing.JLabel();
        E_3 = new javax.swing.JLabel();
        B_8 = new javax.swing.JLabel();
        C_3 = new javax.swing.JLabel();
        C_8 = new javax.swing.JLabel();
        B_3 = new javax.swing.JLabel();
        D_8 = new javax.swing.JLabel();
        A_3 = new javax.swing.JLabel();
        F_8 = new javax.swing.JLabel();
        A_2 = new javax.swing.JLabel();
        E_8 = new javax.swing.JLabel();
        G_8 = new javax.swing.JLabel();
        H_8 = new javax.swing.JLabel();
        H_7 = new javax.swing.JLabel();
        B_2 = new javax.swing.JLabel();
        C_2 = new javax.swing.JLabel();
        D_2 = new javax.swing.JLabel();
        E_2 = new javax.swing.JLabel();
        G_7 = new javax.swing.JLabel();
        F_2 = new javax.swing.JLabel();
        F_7 = new javax.swing.JLabel();
        H_2 = new javax.swing.JLabel();
        E_7 = new javax.swing.JLabel();
        G_2 = new javax.swing.JLabel();
        D_7 = new javax.swing.JLabel();
        H_1 = new javax.swing.JLabel();
        C_7 = new javax.swing.JLabel();
        G_1 = new javax.swing.JLabel();
        B_7 = new javax.swing.JLabel();
        F_1 = new javax.swing.JLabel();
        A_7 = new javax.swing.JLabel();
        A_6 = new javax.swing.JLabel();
        B_6 = new javax.swing.JLabel();
        C_6 = new javax.swing.JLabel();
        E_1 = new javax.swing.JLabel();
        D_1 = new javax.swing.JLabel();
        C_1 = new javax.swing.JLabel();
        B_1 = new javax.swing.JLabel();
        D_6 = new javax.swing.JLabel();
        A_1 = new javax.swing.JLabel();
        E_6 = new javax.swing.JLabel();
        F_6 = new javax.swing.JLabel();
        G_6 = new javax.swing.JLabel();
        H_6 = new javax.swing.JLabel();
        H_5 = new javax.swing.JLabel();
        G_5 = new javax.swing.JLabel();
        F_5 = new javax.swing.JLabel();
        E_5 = new javax.swing.JLabel();
        D_5 = new javax.swing.JLabel();
        B_5 = new javax.swing.JLabel();
        C_5 = new javax.swing.JLabel();
        A_5 = new javax.swing.JLabel();
        A_4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Oracle");
        setMaximumSize(new java.awt.Dimension(680, 552));
        setMinimumSize(new java.awt.Dimension(680, 552));
        setResizable(false);

        jButton1.setText("Peón Negro");
        jButton1.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Caballo Negro");
        jButton2.setPreferredSize(new java.awt.Dimension(110, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Rey Negro");
        jButton3.setPreferredSize(new java.awt.Dimension(110, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Peón Blanco");
        jButton4.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Caballo Blanco");
        jButton5.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Rey Blanco");
        jButton6.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Mapear");

        back.setTitle("Tablero");
        back.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/kingw.png"))); // NOI18N
        back.setVisible(true);
        back.getContentPane().setLayout(null);

        B_4.setBackground(new java.awt.Color(0, 0, 0));
        B_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        B_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_4);
        B_4.setBounds(50, 200, 50, 50);

        C_4.setBackground(new java.awt.Color(255, 255, 255));
        C_4.setForeground(new java.awt.Color(255, 255, 255));
        C_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        C_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_4);
        C_4.setBounds(100, 200, 50, 50);

        D_4.setBackground(new java.awt.Color(0, 0, 0));
        D_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        D_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_4);
        D_4.setBounds(150, 200, 50, 50);

        E_4.setBackground(new java.awt.Color(255, 255, 255));
        E_4.setForeground(new java.awt.Color(255, 255, 255));
        E_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        E_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_4);
        E_4.setBounds(200, 200, 50, 50);

        F_4.setBackground(new java.awt.Color(0, 0, 0));
        F_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        F_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_4);
        F_4.setBounds(250, 200, 50, 50);

        H_4.setBackground(new java.awt.Color(0, 0, 0));
        H_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        H_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_4);
        H_4.setBounds(350, 200, 50, 50);

        G_4.setBackground(new java.awt.Color(255, 255, 255));
        G_4.setForeground(new java.awt.Color(255, 255, 255));
        G_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        G_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_4);
        G_4.setBounds(300, 200, 50, 50);

        H_3.setBackground(new java.awt.Color(255, 255, 255));
        H_3.setForeground(new java.awt.Color(255, 255, 255));
        H_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        H_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_3);
        H_3.setBounds(350, 250, 50, 50);

        G_3.setBackground(new java.awt.Color(0, 0, 0));
        G_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        G_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_3);
        G_3.setBounds(300, 250, 50, 50);

        F_3.setBackground(new java.awt.Color(255, 255, 255));
        F_3.setForeground(new java.awt.Color(255, 255, 255));
        F_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        F_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_3);
        F_3.setBounds(250, 250, 50, 50);

        D_3.setBackground(new java.awt.Color(255, 255, 255));
        D_3.setForeground(new java.awt.Color(255, 255, 255));
        D_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        D_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_3);
        D_3.setBounds(150, 250, 50, 50);

        A_8.setBackground(new java.awt.Color(255, 255, 255));
        A_8.setForeground(new java.awt.Color(255, 255, 255));
        A_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        A_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.getContentPane().add(A_8);
        A_8.setBounds(0, 0, 50, 50);

        E_3.setBackground(new java.awt.Color(0, 0, 0));
        E_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        E_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_3);
        E_3.setBounds(200, 250, 50, 50);

        B_8.setBackground(new java.awt.Color(0, 0, 0));
        B_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        B_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_8);
        B_8.setBounds(50, 0, 50, 50);

        C_3.setBackground(new java.awt.Color(0, 0, 0));
        C_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        C_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_3);
        C_3.setBounds(100, 250, 50, 50);

        C_8.setBackground(new java.awt.Color(255, 255, 255));
        C_8.setForeground(new java.awt.Color(255, 255, 255));
        C_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        C_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_8);
        C_8.setBounds(100, 0, 50, 50);

        B_3.setBackground(new java.awt.Color(255, 255, 255));
        B_3.setForeground(new java.awt.Color(255, 255, 255));
        B_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        B_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_3);
        B_3.setBounds(50, 250, 50, 50);

        D_8.setBackground(new java.awt.Color(0, 0, 0));
        D_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        D_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_8);
        D_8.setBounds(150, 0, 50, 50);

        A_3.setBackground(new java.awt.Color(0, 0, 0));
        A_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        A_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_3);
        A_3.setBounds(0, 250, 50, 50);

        F_8.setBackground(new java.awt.Color(0, 0, 0));
        F_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        F_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_8);
        F_8.setBounds(250, 0, 50, 50);

        A_2.setBackground(new java.awt.Color(255, 255, 255));
        A_2.setForeground(new java.awt.Color(255, 255, 255));
        A_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        A_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_2);
        A_2.setBounds(0, 300, 50, 50);

        E_8.setBackground(new java.awt.Color(255, 255, 255));
        E_8.setForeground(new java.awt.Color(255, 255, 255));
        E_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        E_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_8);
        E_8.setBounds(200, 0, 50, 50);

        G_8.setBackground(new java.awt.Color(255, 255, 255));
        G_8.setForeground(new java.awt.Color(255, 255, 255));
        G_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        G_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_8);
        G_8.setBounds(300, 0, 50, 50);

        H_8.setBackground(new java.awt.Color(0, 0, 0));
        H_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        H_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_8);
        H_8.setBounds(350, 0, 50, 50);

        H_7.setBackground(new java.awt.Color(255, 255, 255));
        H_7.setForeground(new java.awt.Color(255, 255, 255));
        H_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        H_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_7);
        H_7.setBounds(350, 50, 50, 50);

        B_2.setBackground(new java.awt.Color(0, 0, 0));
        B_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        B_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_2);
        B_2.setBounds(50, 300, 50, 50);

        C_2.setBackground(new java.awt.Color(255, 255, 255));
        C_2.setForeground(new java.awt.Color(255, 255, 255));
        C_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        C_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_2);
        C_2.setBounds(100, 300, 50, 50);

        D_2.setBackground(new java.awt.Color(0, 0, 0));
        D_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        D_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_2);
        D_2.setBounds(150, 300, 50, 50);

        E_2.setBackground(new java.awt.Color(255, 255, 255));
        E_2.setForeground(new java.awt.Color(255, 255, 255));
        E_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        E_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_2);
        E_2.setBounds(200, 300, 50, 50);

        G_7.setBackground(new java.awt.Color(0, 0, 0));
        G_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        G_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_7);
        G_7.setBounds(300, 50, 50, 50);

        F_2.setBackground(new java.awt.Color(0, 0, 0));
        F_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        F_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_2);
        F_2.setBounds(250, 300, 50, 50);

        F_7.setBackground(new java.awt.Color(255, 255, 255));
        F_7.setForeground(new java.awt.Color(255, 255, 255));
        F_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        F_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_7);
        F_7.setBounds(250, 50, 50, 50);

        H_2.setBackground(new java.awt.Color(0, 0, 0));
        H_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        H_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_2);
        H_2.setBounds(350, 300, 50, 50);

        E_7.setBackground(new java.awt.Color(0, 0, 0));
        E_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        E_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_7);
        E_7.setBounds(200, 50, 50, 50);

        G_2.setBackground(new java.awt.Color(255, 255, 255));
        G_2.setForeground(new java.awt.Color(255, 255, 255));
        G_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        G_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_2);
        G_2.setBounds(300, 300, 50, 50);

        D_7.setBackground(new java.awt.Color(255, 255, 255));
        D_7.setForeground(new java.awt.Color(255, 255, 255));
        D_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        D_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_7);
        D_7.setBounds(150, 50, 50, 50);

        H_1.setBackground(new java.awt.Color(255, 255, 255));
        H_1.setForeground(new java.awt.Color(255, 255, 255));
        H_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        H_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_1);
        H_1.setBounds(350, 350, 50, 50);

        C_7.setBackground(new java.awt.Color(0, 0, 0));
        C_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        C_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_7);
        C_7.setBounds(100, 50, 50, 50);

        G_1.setBackground(new java.awt.Color(0, 0, 0));
        G_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        G_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_1);
        G_1.setBounds(300, 350, 50, 50);

        B_7.setBackground(new java.awt.Color(255, 255, 255));
        B_7.setForeground(new java.awt.Color(255, 255, 255));
        B_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        B_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_7);
        B_7.setBounds(50, 50, 50, 50);

        F_1.setBackground(new java.awt.Color(255, 255, 255));
        F_1.setForeground(new java.awt.Color(255, 255, 255));
        F_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        F_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_1);
        F_1.setBounds(250, 350, 50, 50);

        A_7.setBackground(new java.awt.Color(0, 0, 0));
        A_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        A_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_7);
        A_7.setBounds(0, 50, 50, 50);

        A_6.setBackground(new java.awt.Color(255, 255, 255));
        A_6.setForeground(new java.awt.Color(255, 255, 255));
        A_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        A_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_6);
        A_6.setBounds(0, 100, 50, 50);

        B_6.setBackground(new java.awt.Color(0, 0, 0));
        B_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        B_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_6);
        B_6.setBounds(50, 100, 50, 50);

        C_6.setBackground(new java.awt.Color(255, 255, 255));
        C_6.setForeground(new java.awt.Color(255, 255, 255));
        C_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        C_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_6);
        C_6.setBounds(100, 100, 50, 50);

        E_1.setBackground(new java.awt.Color(0, 0, 0));
        E_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        E_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_1);
        E_1.setBounds(200, 350, 50, 50);

        D_1.setBackground(new java.awt.Color(255, 255, 255));
        D_1.setForeground(new java.awt.Color(255, 255, 255));
        D_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        D_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_1);
        D_1.setBounds(150, 350, 50, 50);

        C_1.setBackground(new java.awt.Color(0, 0, 0));
        C_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        C_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_1);
        C_1.setBounds(100, 350, 50, 50);

        B_1.setBackground(new java.awt.Color(255, 255, 255));
        B_1.setForeground(new java.awt.Color(255, 255, 255));
        B_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        B_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_1);
        B_1.setBounds(50, 350, 50, 50);

        D_6.setBackground(new java.awt.Color(0, 0, 0));
        D_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        D_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_6);
        D_6.setBounds(150, 100, 50, 50);

        A_1.setBackground(new java.awt.Color(0, 0, 0));
        A_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        A_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_1);
        A_1.setBounds(0, 350, 50, 50);

        E_6.setBackground(new java.awt.Color(255, 255, 255));
        E_6.setForeground(new java.awt.Color(255, 255, 255));
        E_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        E_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_6);
        E_6.setBounds(200, 100, 50, 50);

        F_6.setBackground(new java.awt.Color(0, 0, 0));
        F_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        F_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_6);
        F_6.setBounds(250, 100, 50, 50);

        G_6.setBackground(new java.awt.Color(255, 255, 255));
        G_6.setForeground(new java.awt.Color(255, 255, 255));
        G_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        G_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_6);
        G_6.setBounds(300, 100, 50, 50);

        H_6.setBackground(new java.awt.Color(0, 0, 0));
        H_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        H_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_6);
        H_6.setBounds(350, 100, 50, 50);

        H_5.setBackground(new java.awt.Color(255, 255, 255));
        H_5.setForeground(new java.awt.Color(255, 255, 255));
        H_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        H_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(H_5);
        H_5.setBounds(350, 150, 50, 50);

        G_5.setBackground(new java.awt.Color(0, 0, 0));
        G_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        G_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(G_5);
        G_5.setBounds(300, 150, 50, 50);

        F_5.setBackground(new java.awt.Color(255, 255, 255));
        F_5.setForeground(new java.awt.Color(255, 255, 255));
        F_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        F_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(F_5);
        F_5.setBounds(250, 150, 50, 50);

        E_5.setBackground(new java.awt.Color(0, 0, 0));
        E_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        E_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(E_5);
        E_5.setBounds(200, 150, 50, 50);

        D_5.setBackground(new java.awt.Color(255, 255, 255));
        D_5.setForeground(new java.awt.Color(255, 255, 255));
        D_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        D_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(D_5);
        D_5.setBounds(150, 150, 50, 50);

        B_5.setBackground(new java.awt.Color(255, 255, 255));
        B_5.setForeground(new java.awt.Color(255, 255, 255));
        B_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        B_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(B_5);
        B_5.setBounds(50, 150, 50, 50);

        C_5.setBackground(new java.awt.Color(0, 0, 0));
        C_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        C_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(C_5);
        C_5.setBounds(100, 150, 50, 50);

        A_5.setBackground(new java.awt.Color(0, 0, 0));
        A_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/black.jpg"))); // NOI18N
        A_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_5);
        A_5.setBounds(0, 150, 50, 50);

        A_4.setBackground(new java.awt.Color(255, 255, 255));
        A_4.setForeground(new java.awt.Color(255, 255, 255));
        A_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/white.jpg"))); // NOI18N
        A_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(A_4);
        A_4.setBounds(0, 200, 50, 50);

        background.setFocusable(false);
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClick(evt);
            }
        });
        back.getContentPane().add(background);
        background.setBounds(0, 0, 400, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(468, 468, 468))))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_8MouseClicked
        if (evt.isMetaDown()) {
            System.out.println("Yeah");
        }
    }//GEN-LAST:event_A_8MouseClicked

    private void A_8MouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_8MouseClick
        if (evt.isMetaDown()) {
            System.out.println("Yeah");
        }
    }//GEN-LAST:event_A_8MouseClick

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (peonesNegros.size()>8) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 8 peones en el tablero"
                    , "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (caballosNegros.size()>2) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 2 caballos en el tablero"
                    , "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (peonesBlancos.size()>8) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 8 peones en el tablero"
                    , "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (caballosBlancos.size()>2) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 2 caballos en el tablero"
                    , "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_1;
    private javax.swing.JLabel A_2;
    private javax.swing.JLabel A_3;
    private javax.swing.JLabel A_4;
    private javax.swing.JLabel A_5;
    private javax.swing.JLabel A_6;
    private javax.swing.JLabel A_7;
    private javax.swing.JLabel A_8;
    private javax.swing.JLabel B_1;
    private javax.swing.JLabel B_2;
    private javax.swing.JLabel B_3;
    private javax.swing.JLabel B_4;
    private javax.swing.JLabel B_5;
    private javax.swing.JLabel B_6;
    private javax.swing.JLabel B_7;
    private javax.swing.JLabel B_8;
    private javax.swing.JLabel C_1;
    private javax.swing.JLabel C_2;
    private javax.swing.JLabel C_3;
    private javax.swing.JLabel C_4;
    private javax.swing.JLabel C_5;
    private javax.swing.JLabel C_6;
    private javax.swing.JLabel C_7;
    private javax.swing.JLabel C_8;
    private javax.swing.JLabel D_1;
    private javax.swing.JLabel D_2;
    private javax.swing.JLabel D_3;
    private javax.swing.JLabel D_4;
    private javax.swing.JLabel D_5;
    private javax.swing.JLabel D_6;
    private javax.swing.JLabel D_7;
    private javax.swing.JLabel D_8;
    private javax.swing.JLabel E_1;
    private javax.swing.JLabel E_2;
    private javax.swing.JLabel E_3;
    private javax.swing.JLabel E_4;
    private javax.swing.JLabel E_5;
    private javax.swing.JLabel E_6;
    private javax.swing.JLabel E_7;
    private javax.swing.JLabel E_8;
    private javax.swing.JLabel F_1;
    private javax.swing.JLabel F_2;
    private javax.swing.JLabel F_3;
    private javax.swing.JLabel F_4;
    private javax.swing.JLabel F_5;
    private javax.swing.JLabel F_6;
    private javax.swing.JLabel F_7;
    private javax.swing.JLabel F_8;
    private javax.swing.JLabel G_1;
    private javax.swing.JLabel G_2;
    private javax.swing.JLabel G_3;
    private javax.swing.JLabel G_4;
    private javax.swing.JLabel G_5;
    private javax.swing.JLabel G_6;
    private javax.swing.JLabel G_7;
    private javax.swing.JLabel G_8;
    private javax.swing.JLabel H_1;
    private javax.swing.JLabel H_2;
    private javax.swing.JLabel H_3;
    private javax.swing.JLabel H_4;
    private javax.swing.JLabel H_5;
    private javax.swing.JLabel H_6;
    private javax.swing.JLabel H_7;
    private javax.swing.JLabel H_8;
    private javax.swing.JInternalFrame back;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
}
