/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2_estructura;

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Principal extends javax.swing.JFrame {

    List caballosBlancos = new List();
    List caballosNegros = new List();
    List peonesBlancos = new List();
    List peonesNegros = new List();
    ImageIcon kingWhite = new ImageIcon("./src/project2_estructura/Kingw.png");
    ImageIcon pawnWhite = new ImageIcon("./src/project2_estructura/Pawnw.png");
    ImageIcon knightWhite = new ImageIcon("./src/project2_estructura/Knightw.png");
    ImageIcon kingBlack = new ImageIcon("./src/project2_estructura/Kingb.png");
    ImageIcon pawnBlack = new ImageIcon("./src/project2_estructura/Pawnb.png");
    ImageIcon knightBlack = new ImageIcon("./src/project2_estructura/Knightb.png");
    JLabel tmp = null;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        addPiece = new javax.swing.JMenu();
        addWhiteKing = new javax.swing.JMenuItem();
        addWhiteKnight = new javax.swing.JMenuItem();
        addWhitePawn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        addBlackKing = new javax.swing.JMenuItem();
        addBlackKnight = new javax.swing.JMenuItem();
        addBlackPawn = new javax.swing.JMenuItem();
        removePiece = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        back = new javax.swing.JPanel();
        A_8 = new javax.swing.JLabel();
        A_7 = new javax.swing.JLabel();
        A_6 = new javax.swing.JLabel();
        A_5 = new javax.swing.JLabel();
        A_4 = new javax.swing.JLabel();
        A_3 = new javax.swing.JLabel();
        A_2 = new javax.swing.JLabel();
        A_1 = new javax.swing.JLabel();
        B_8 = new javax.swing.JLabel();
        B_7 = new javax.swing.JLabel();
        B_6 = new javax.swing.JLabel();
        B_5 = new javax.swing.JLabel();
        B_4 = new javax.swing.JLabel();
        B_3 = new javax.swing.JLabel();
        B_2 = new javax.swing.JLabel();
        B_1 = new javax.swing.JLabel();
        C_8 = new javax.swing.JLabel();
        C_7 = new javax.swing.JLabel();
        C_6 = new javax.swing.JLabel();
        C_5 = new javax.swing.JLabel();
        C_4 = new javax.swing.JLabel();
        C_3 = new javax.swing.JLabel();
        C_2 = new javax.swing.JLabel();
        C_1 = new javax.swing.JLabel();
        D_8 = new javax.swing.JLabel();
        D_7 = new javax.swing.JLabel();
        D_6 = new javax.swing.JLabel();
        D_5 = new javax.swing.JLabel();
        D_4 = new javax.swing.JLabel();
        D_3 = new javax.swing.JLabel();
        D_2 = new javax.swing.JLabel();
        D_1 = new javax.swing.JLabel();
        E_8 = new javax.swing.JLabel();
        E_7 = new javax.swing.JLabel();
        E_6 = new javax.swing.JLabel();
        E_5 = new javax.swing.JLabel();
        E_4 = new javax.swing.JLabel();
        E_3 = new javax.swing.JLabel();
        E_2 = new javax.swing.JLabel();
        E_1 = new javax.swing.JLabel();
        F_8 = new javax.swing.JLabel();
        F_7 = new javax.swing.JLabel();
        F_6 = new javax.swing.JLabel();
        F_5 = new javax.swing.JLabel();
        F_4 = new javax.swing.JLabel();
        F_3 = new javax.swing.JLabel();
        F_2 = new javax.swing.JLabel();
        F_1 = new javax.swing.JLabel();
        G_8 = new javax.swing.JLabel();
        G_7 = new javax.swing.JLabel();
        G_6 = new javax.swing.JLabel();
        G_5 = new javax.swing.JLabel();
        G_4 = new javax.swing.JLabel();
        G_3 = new javax.swing.JLabel();
        G_2 = new javax.swing.JLabel();
        G_1 = new javax.swing.JLabel();
        H_8 = new javax.swing.JLabel();
        H_7 = new javax.swing.JLabel();
        H_6 = new javax.swing.JLabel();
        H_5 = new javax.swing.JLabel();
        H_4 = new javax.swing.JLabel();
        H_3 = new javax.swing.JLabel();
        H_2 = new javax.swing.JLabel();
        H_1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        addPiece.setText("Agregar");

        addWhiteKing.setText("Rey Blanco");
        addWhiteKing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWhiteKingActionPerformed(evt);
            }
        });
        addPiece.add(addWhiteKing);

        addWhiteKnight.setText("Caballo Blanco");
        addWhiteKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWhiteKnightActionPerformed(evt);
            }
        });
        addPiece.add(addWhiteKnight);

        addWhitePawn.setText("Peon Blanco");
        addWhitePawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWhitePawnActionPerformed(evt);
            }
        });
        addPiece.add(addWhitePawn);
        addPiece.add(jSeparator1);

        addBlackKing.setText("Rey Negro");
        addBlackKing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBlackKingActionPerformed(evt);
            }
        });
        addPiece.add(addBlackKing);

        addBlackKnight.setText("Caballo Negro");
        addBlackKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBlackKnightActionPerformed(evt);
            }
        });
        addPiece.add(addBlackKnight);

        addBlackPawn.setText("Peon Negro");
        addBlackPawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBlackPawnActionPerformed(evt);
            }
        });
        addPiece.add(addBlackPawn);

        menu.add(addPiece);

        removePiece.setText("Quitar");
        removePiece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePieceActionPerformed(evt);
            }
        });
        menu.add(removePiece);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Oracle");
        setMaximumSize(new java.awt.Dimension(680, 552));
        setMinimumSize(new java.awt.Dimension(680, 552));
        setResizable(false);

        jButton1.setText("Peón Negro");
        jButton1.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Caballo Negro");
        jButton2.setPreferredSize(new java.awt.Dimension(110, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Rey Negro");
        jButton3.setPreferredSize(new java.awt.Dimension(110, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Peón Blanco");
        jButton4.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Caballo Blanco");
        jButton5.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Rey Blanco");
        jButton6.setPreferredSize(new java.awt.Dimension(115, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Mapear");

        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_8.setName("18");
        A_8.setBackground(new java.awt.Color(255, 255, 255));
        A_8.setForeground(new java.awt.Color(255, 255, 255));
        A_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        A_7.setName("17");
        A_7.setBackground(new java.awt.Color(0, 0, 0));
        A_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 50));

        A_6.setName("16");
        A_6.setBackground(new java.awt.Color(255, 255, 255));
        A_6.setForeground(new java.awt.Color(255, 255, 255));
        A_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 50));

        A_5.setName("15");
        A_5.setBackground(new java.awt.Color(0, 0, 0));
        A_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 50, 50));

        A_4.setName("14");
        A_4.setBackground(new java.awt.Color(255, 255, 255));
        A_4.setForeground(new java.awt.Color(255, 255, 255));
        A_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, 50));

        A_3.setName("13");
        A_3.setBackground(new java.awt.Color(0, 0, 0));
        A_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 50));

        A_2.setName("12");
        A_2.setBackground(new java.awt.Color(255, 255, 255));
        A_2.setForeground(new java.awt.Color(255, 255, 255));
        A_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 50));

        A_1.setName("11");
        A_1.setBackground(new java.awt.Color(0, 0, 0));
        A_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(A_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 50, 50));

        B_8.setName("28");
        B_8.setBackground(new java.awt.Color(0, 0, 0));
        B_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        B_7.setName("27");
        B_7.setBackground(new java.awt.Color(255, 255, 255));
        B_7.setForeground(new java.awt.Color(255, 255, 255));
        B_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 50));

        B_6.setName("26");
        B_6.setBackground(new java.awt.Color(0, 0, 0));
        B_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 50));

        B_5.setName("25");
        B_5.setBackground(new java.awt.Color(255, 255, 255));
        B_5.setForeground(new java.awt.Color(255, 255, 255));
        B_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 50, 50));

        B_4.setName("24");
        B_4.setBackground(new java.awt.Color(0, 0, 0));
        B_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, 50));

        B_3.setName("23");
        B_3.setBackground(new java.awt.Color(255, 255, 255));
        B_3.setForeground(new java.awt.Color(255, 255, 255));
        B_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 50, 50));

        B_2.setName("22");
        B_2.setBackground(new java.awt.Color(0, 0, 0));
        B_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 50, 50));

        B_1.setName("21");
        B_1.setBackground(new java.awt.Color(255, 255, 255));
        B_1.setForeground(new java.awt.Color(255, 255, 255));
        B_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(B_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 50, 50));

        C_8.setName("38");
        C_8.setBackground(new java.awt.Color(255, 255, 255));
        C_8.setForeground(new java.awt.Color(255, 255, 255));
        C_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        C_7.setName("37");
        C_7.setBackground(new java.awt.Color(0, 0, 0));
        C_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 50));

        C_6.setName("36");
        C_6.setBackground(new java.awt.Color(255, 255, 255));
        C_6.setForeground(new java.awt.Color(255, 255, 255));
        C_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        C_5.setName("35");
        C_5.setBackground(new java.awt.Color(0, 0, 0));
        C_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 50));

        C_4.setName("34");
        C_4.setBackground(new java.awt.Color(255, 255, 255));
        C_4.setForeground(new java.awt.Color(255, 255, 255));
        C_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 50, 50));

        C_3.setName("33");
        C_3.setBackground(new java.awt.Color(0, 0, 0));
        C_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 50, 50));

        C_2.setName("32");
        C_2.setBackground(new java.awt.Color(255, 255, 255));
        C_2.setForeground(new java.awt.Color(255, 255, 255));
        C_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 50, 50));

        C_1.setName("31");
        C_1.setBackground(new java.awt.Color(0, 0, 0));
        C_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(C_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 50, 50));

        D_8.setName("48");
        D_8.setBackground(new java.awt.Color(0, 0, 0));
        D_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 50, 50));

        D_7.setName("47");
        D_7.setBackground(new java.awt.Color(255, 255, 255));
        D_7.setForeground(new java.awt.Color(255, 255, 255));
        D_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 50));

        D_6.setName("46");
        D_6.setBackground(new java.awt.Color(0, 0, 0));
        D_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, 50));

        D_5.setName("45");
        D_5.setBackground(new java.awt.Color(255, 255, 255));
        D_5.setForeground(new java.awt.Color(255, 255, 255));
        D_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, 50));

        D_4.setName("44");
        D_4.setBackground(new java.awt.Color(0, 0, 0));
        D_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 50));

        D_3.setName("43");
        D_3.setBackground(new java.awt.Color(255, 255, 255));
        D_3.setForeground(new java.awt.Color(255, 255, 255));
        D_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 50));

        D_2.setName("42");
        D_2.setBackground(new java.awt.Color(0, 0, 0));
        D_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 50, 50));

        D_1.setName("41");
        D_1.setBackground(new java.awt.Color(255, 255, 255));
        D_1.setForeground(new java.awt.Color(255, 255, 255));
        D_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(D_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, 50));

        E_8.setName("58");
        E_8.setBackground(new java.awt.Color(255, 255, 255));
        E_8.setForeground(new java.awt.Color(255, 255, 255));
        E_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 50, 50));

        E_7.setName("57");
        E_7.setBackground(new java.awt.Color(0, 0, 0));
        E_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, 50));

        E_6.setName("56");
        E_6.setBackground(new java.awt.Color(255, 255, 255));
        E_6.setForeground(new java.awt.Color(255, 255, 255));
        E_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 50, 50));

        E_5.setName("55");
        E_5.setBackground(new java.awt.Color(0, 0, 0));
        E_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 50));

        E_4.setName("54");
        E_4.setBackground(new java.awt.Color(255, 255, 255));
        E_4.setForeground(new java.awt.Color(255, 255, 255));
        E_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 50, 50));

        E_3.setName("53");
        E_3.setBackground(new java.awt.Color(0, 0, 0));
        E_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 50, 50));

        E_2.setName("52");
        E_2.setBackground(new java.awt.Color(255, 255, 255));
        E_2.setForeground(new java.awt.Color(255, 255, 255));
        E_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 50, 50));

        E_1.setName("51");
        E_1.setBackground(new java.awt.Color(0, 0, 0));
        E_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        E_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(E_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 50, 50));

        F_8.setName("68");
        F_8.setBackground(new java.awt.Color(0, 0, 0));
        F_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

        F_7.setName("67");
        F_7.setBackground(new java.awt.Color(255, 255, 255));
        F_7.setForeground(new java.awt.Color(255, 255, 255));
        F_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 50));

        F_6.setName("66");
        F_6.setBackground(new java.awt.Color(0, 0, 0));
        F_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 50, 50));

        F_5.setName("65");
        F_5.setBackground(new java.awt.Color(255, 255, 255));
        F_5.setForeground(new java.awt.Color(255, 255, 255));
        F_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 50, 50));

        F_4.setName("64");
        F_4.setBackground(new java.awt.Color(0, 0, 0));
        F_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 50, 50));

        F_3.setName("63");
        F_3.setBackground(new java.awt.Color(255, 255, 255));
        F_3.setForeground(new java.awt.Color(255, 255, 255));
        F_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 50, 50));

        F_2.setName("62");
        F_2.setBackground(new java.awt.Color(0, 0, 0));
        F_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 50, 50));

        F_1.setName("61");
        F_1.setBackground(new java.awt.Color(255, 255, 255));
        F_1.setForeground(new java.awt.Color(255, 255, 255));
        F_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        F_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(F_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 50, 50));

        G_8.setName("78");
        G_8.setBackground(new java.awt.Color(255, 255, 255));
        G_8.setForeground(new java.awt.Color(255, 255, 255));
        G_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 50, 50));

        G_7.setName("77");
        G_7.setBackground(new java.awt.Color(0, 0, 0));
        G_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, 50));

        G_6.setName("76");
        G_6.setBackground(new java.awt.Color(255, 255, 255));
        G_6.setForeground(new java.awt.Color(255, 255, 255));
        G_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 50, 50));

        G_5.setName("75");
        G_5.setBackground(new java.awt.Color(0, 0, 0));
        G_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 50, 50));

        G_4.setName("74");
        G_4.setBackground(new java.awt.Color(255, 255, 255));
        G_4.setForeground(new java.awt.Color(255, 255, 255));
        G_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 50, 50));

        G_3.setName("73");
        G_3.setBackground(new java.awt.Color(0, 0, 0));
        G_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 50, 50));

        G_2.setName("72");
        G_2.setBackground(new java.awt.Color(255, 255, 255));
        G_2.setForeground(new java.awt.Color(255, 255, 255));
        G_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 50, 50));

        G_1.setName("71");
        G_1.setBackground(new java.awt.Color(0, 0, 0));
        G_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        G_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        G_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(G_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 50, 50));

        H_8.setName("88");
        H_8.setBackground(new java.awt.Color(0, 0, 0));
        H_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 50));

        H_7.setName("87");
        H_7.setBackground(new java.awt.Color(255, 255, 255));
        H_7.setForeground(new java.awt.Color(255, 255, 255));
        H_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 50, 50));

        H_6.setName("86");
        H_6.setBackground(new java.awt.Color(0, 0, 0));
        H_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 50, 50));

        H_5.setName("85");
        H_5.setBackground(new java.awt.Color(255, 255, 255));
        H_5.setForeground(new java.awt.Color(255, 255, 255));
        H_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 50, 50));

        H_4.setName("84");
        H_4.setBackground(new java.awt.Color(0, 0, 0));
        H_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 50));

        H_3.setName("83");
        H_3.setBackground(new java.awt.Color(255, 255, 255));
        H_3.setForeground(new java.awt.Color(255, 255, 255));
        H_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 50, 50));

        H_2.setName("82");
        H_2.setBackground(new java.awt.Color(0, 0, 0));
        H_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 50, 50));

        H_1.setName("81");
        H_1.setBackground(new java.awt.Color(255, 255, 255));
        H_1.setForeground(new java.awt.Color(255, 255, 255));
        H_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        H_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        H_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_8MouseClicked(evt);
            }
        });
        back.add(H_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 50, 50));

        background.setName("back");
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2_estructura/background.png"))); // NOI18N
        background.setFocusable(false);
        back.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton7)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (peonesNegros.size() > 8) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 8 peones en el tablero", "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (caballosNegros.size() > 2) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 2 caballos en el tablero", "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (peonesBlancos.size() > 8) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 8 peones en el tablero", "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (caballosBlancos.size() > 2) {
            JOptionPane.showMessageDialog(this, "No se pueden poner mas de 2 caballos en el tablero", "Limite de Piezas", 0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void A_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_8MouseClicked
        if (evt.isMetaDown()) {
            this.menu.show(evt.getComponent(), evt.getX(), evt.getY());
            tmp = (JLabel) evt.getComponent();
        }
    }//GEN-LAST:event_A_8MouseClicked

    private void addWhiteKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWhiteKingActionPerformed
        if (tmp != null) {
            if (verify("KingWhite")) {
                tmp.setIcon(kingWhite);
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addWhiteKingActionPerformed

    private void addWhiteKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWhiteKnightActionPerformed
        if (tmp != null) {
            if (verify("KnightWhite")) {
                tmp.setIcon(knightWhite);
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addWhiteKnightActionPerformed

    private void addWhitePawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWhitePawnActionPerformed
        if (tmp != null) {
            if (verify("PawnWhite")) {
                tmp.setIcon(pawnWhite);
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addWhitePawnActionPerformed

    private void addBlackKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBlackKingActionPerformed
        if (tmp != null) {
            if (verify("KingBlack")) {
                tmp.setIcon(kingBlack);
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBlackKingActionPerformed

    private void addBlackKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBlackKnightActionPerformed
        if (tmp != null) {
            if (verify("KnightBlack")) {
                tmp.setIcon(knightWhite);
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBlackKnightActionPerformed

    private void addBlackPawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBlackPawnActionPerformed
        if (tmp != null) {
            if (verify("PawnBlack")) {
                tmp.setIcon(pawnBlack);
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBlackPawnActionPerformed

    private void removePieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePieceActionPerformed
        if (tmp != null) {
            if (tmp.getIcon() != null) {
                for (int i = 0; i < this.back.getComponents().length; i++) {
                    if (this.back.getComponents()[i] == tmp) {
                        ((JLabel) this.back.getComponents()[i]).setIcon(null);
                    }
                }
                tmp = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error\nNo ha Seleccionado un Espacio del Tablero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removePieceActionPerformed

    private Board generate() {
        Board Board = new Board();
        Component[] Labels = this.back.getComponents();
        int x, y;
        for (Component Label: Labels) {
            x = Integer.parseInt(Label.getName().split("")[0]);
            y = Integer.parseInt(Label.getName().split("")[1]);
            if ((ImageIcon) ((JLabel) Label).getIcon() == this.kingWhite) {
                Board.addPiece(new King(x, y, true));
            } else if ((ImageIcon) ((JLabel) Label).getIcon() == this.kingBlack) {
                Board.addPiece(new King(x, y, false));
            } else if ((ImageIcon) ((JLabel) Label).getIcon() == this.knightWhite) {
                Board.addPiece(new Knight(x, y, true));
            } else if ((ImageIcon) ((JLabel) Label).getIcon() == this.knightBlack) {
                Board.addPiece(new Knight(x, y, false));
            } else if ((ImageIcon) ((JLabel) Label).getIcon() == this.pawnWhite) {
                Board.addPiece(new Pawn(x, y, true));
            } else if ((ImageIcon) ((JLabel) Label).getIcon() == this.pawnBlack) {
                Board.addPiece(new Pawn(x, y, false));
            }
            
        }
        return null;
    }

    private boolean verify(String piece) {
        Component[] Labels = this.back.getComponents();
        int Kingw = 0, Kingb = 0, Knightw = 0, Knightb = 0, Pawnw = 0, Pawnb = 0;
        ImageIcon Image;
        for (Component Label : Labels) {
            Image = (ImageIcon) ((JLabel) Label).getIcon();
            if (Image == this.kingWhite) {
                Kingw++;
            } else if (Image == this.kingBlack) {
                Kingb++;
            } else if (Image == this.knightWhite) {
                Knightw++;
            } else if (Image == this.knightBlack) {
                Knightb++;
            } else if (Image == this.pawnWhite) {
                Pawnw++;
            } else if (Image == this.pawnBlack) {
                Pawnb++;
            }
        }
        switch (piece) {
            case "KingWhite":{
                if (Kingw == 0) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya hay Agregado un Rey Blanco", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
            case "KingBlack":{
                if (Kingb == 0) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya hay Agregado un Rey Negro", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
            case "KnightWhite":{
                if (Knightw < 2) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya hay Agregado dos Caballos Blancos", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
            case "KnightBlack":{
                if (Knightb < 2) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya hay Agregado dos Caballos Negros", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
            case "PawnWhite":{
                if (Pawnw < 8) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya hay Agregado ocho Peones Blancos", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
            case "PawnBlack":{
                if (Pawnb < 8) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya hay Agregado ocho Peones Negro", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
                }
            }
            break;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_1;
    private javax.swing.JLabel A_2;
    private javax.swing.JLabel A_3;
    private javax.swing.JLabel A_4;
    private javax.swing.JLabel A_5;
    private javax.swing.JLabel A_6;
    private javax.swing.JLabel A_7;
    private javax.swing.JLabel A_8;
    private javax.swing.JLabel B_1;
    private javax.swing.JLabel B_2;
    private javax.swing.JLabel B_3;
    private javax.swing.JLabel B_4;
    private javax.swing.JLabel B_5;
    private javax.swing.JLabel B_6;
    private javax.swing.JLabel B_7;
    private javax.swing.JLabel B_8;
    private javax.swing.JLabel C_1;
    private javax.swing.JLabel C_2;
    private javax.swing.JLabel C_3;
    private javax.swing.JLabel C_4;
    private javax.swing.JLabel C_5;
    private javax.swing.JLabel C_6;
    private javax.swing.JLabel C_7;
    private javax.swing.JLabel C_8;
    private javax.swing.JLabel D_1;
    private javax.swing.JLabel D_2;
    private javax.swing.JLabel D_3;
    private javax.swing.JLabel D_4;
    private javax.swing.JLabel D_5;
    private javax.swing.JLabel D_6;
    private javax.swing.JLabel D_7;
    private javax.swing.JLabel D_8;
    private javax.swing.JLabel E_1;
    private javax.swing.JLabel E_2;
    private javax.swing.JLabel E_3;
    private javax.swing.JLabel E_4;
    private javax.swing.JLabel E_5;
    private javax.swing.JLabel E_6;
    private javax.swing.JLabel E_7;
    private javax.swing.JLabel E_8;
    private javax.swing.JLabel F_1;
    private javax.swing.JLabel F_2;
    private javax.swing.JLabel F_3;
    private javax.swing.JLabel F_4;
    private javax.swing.JLabel F_5;
    private javax.swing.JLabel F_6;
    private javax.swing.JLabel F_7;
    private javax.swing.JLabel F_8;
    private javax.swing.JLabel G_1;
    private javax.swing.JLabel G_2;
    private javax.swing.JLabel G_3;
    private javax.swing.JLabel G_4;
    private javax.swing.JLabel G_5;
    private javax.swing.JLabel G_6;
    private javax.swing.JLabel G_7;
    private javax.swing.JLabel G_8;
    private javax.swing.JLabel H_1;
    private javax.swing.JLabel H_2;
    private javax.swing.JLabel H_3;
    private javax.swing.JLabel H_4;
    private javax.swing.JLabel H_5;
    private javax.swing.JLabel H_6;
    private javax.swing.JLabel H_7;
    private javax.swing.JLabel H_8;
    private javax.swing.JMenuItem addBlackKing;
    private javax.swing.JMenuItem addBlackKnight;
    private javax.swing.JMenuItem addBlackPawn;
    private javax.swing.JMenu addPiece;
    private javax.swing.JMenuItem addWhiteKing;
    private javax.swing.JMenuItem addWhiteKnight;
    private javax.swing.JMenuItem addWhitePawn;
    private javax.swing.JPanel back;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JMenuItem removePiece;
    // End of variables declaration//GEN-END:variables
}
